In [6]:
pip install selenium

Requirement already satisfied: selenium in ./.venv/lib/python3.14/site-packages (4.46.0)
Requirement already satisfied: certifi>=2026.2.25 in ./.venv/lib/python3.14/site-packages (from selenium) (2026.7.22)
Requirement already satisfied: trio<1.0,>=0.31.0 in ./.venv/lib/python3.14/site-packages (from selenium) (0.33.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in ./.venv/lib/python3.14/site-packages (from selenium) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in ./.venv/lib/python3.14/site-packages (from selenium) (4.16.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in ./.venv/lib/python3.14/site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.7.0)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in ./.venv/lib/python3.14/site-packages (from selenium) (1.9.0)
Requirement already satisfied: attrs>=23.2.0 in ./.venv/lib/python3.14/site-packages (from trio<1.0,>=0.31.0->selenium) (26.1.0)
Requirement already satisfied: sortedcontainers in ./.venv/lib/python3.14/site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in ./.venv/lib/python3.14/site-packages (from trio<1.0,>=0.31.0->selenium) (3.18)
Requirement already satisfied: outcome in ./.venv/lib/python3.14/site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in ./.venv/lib/python3.14/site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in ./.venv/lib/python3.14/site-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in ./.venv/lib/python3.14/site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.16.0 in ./.venv/lib/python3.14/site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [7]:
pip install openai

Requirement already satisfied: openai in ./.venv/lib/python3.14/site-packages (2.53.0)
Requirement already satisfied: anyio<5,>=3.5.0 in ./.venv/lib/python3.14/site-packages (from openai) (4.14.2)
Requirement already satisfied: distro<2,>=1.7.0 in ./.venv/lib/python3.14/site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in ./.venv/lib/python3.14/site-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in ./.venv/lib/python3.14/site-packages (from openai) (0.16.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in ./.venv/lib/python3.14/site-packages (from openai) (2.13.4)
Requirement already satisfied: sniffio in ./.venv/lib/python3.14/site-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in ./.venv/lib/python3.14/site-packages (from openai) (4.70.0)
Requirement already satisfied: typing-extensions<5,>=4.14 in ./.venv/lib/python3.14/site-packages (from openai) (4.16.0)
Requirement already satisfied: idna>=2.8 in ./.venv/lib/python3.14/site-packages (from anyio<5,>=3.5.0->openai) (3.18)
Requirement already satisfied: certifi in ./.venv/lib/python3.14/site-packages (from httpx<1,>=0.23.0->openai) (2026.7.22)
Requirement already satisfied: httpcore==1.* in ./.venv/lib/python3.14/site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./.venv/lib/python3.14/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in ./.venv/lib/python3.14/site-packages (from pydantic<3,>=1.9.0->openai) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in ./.venv/lib/python3.14/site-packages (from pydantic<3,>=1.9.0->openai) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in ./.venv/lib/python3.14/site-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [8]:
from bs4 import BeautifulSoup
from time import sleep
import pandas as pd
from dataclasses import dataclass
from urllib.parse import urljoin
from typing import List
import requests
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import openai

In [9]:
#Установим библиотеку BeautifulSoup

In [10]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in ./.venv/lib/python3.14/site-packages (4.15.0)
Requirement already satisfied: soupsieve>=1.6.1 in ./.venv/lib/python3.14/site-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in ./.venv/lib/python3.14/site-packages (from beautifulsoup4) (4.16.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

In [1]:
#Как использовать BeautifulSoup для парсинга веб-страницы:пример

import requests
from bs4 import BeautifulSoup

# Загружаем HTML-код страницы
response = requests.get('https://example.com')
html = response.text

# Создаем объект BeautifulSoup
soup = BeautifulSoup(html, 'html.parser')

# Находим все элементы с тегом 'a'
links = soup.find_all('a')

# Выводим текст и ссылки на найденные элементы
for link in links:
    print(link.text)
    print(link['href'])


#Этот код загружает HTML-код страницы https://example.com, создает объект BeautifulSoup и находит все элементы с тегом 'a'. 
#Затем он выводит текст и ссылки на найденные элементы.

#BeautifulSoup также предоставляет множество других функций и методов для более сложного парсинга и манипуляции с данными. 
#Вы можете узнать больше о библиотеке и ее возможностях в документации BeautifulSoup.

Learn more
https://iana.org/domains/example

In [2]:
from bs4 import BeautifulSoup

html = """
<html>
<head>
<title>Пример страницы</title>
</head>
<body>
<h1>Заголовок страницы</h1>
<p>Это абзац текста.</p>
<a href="https://www.example.com">Ссылка на пример</a>
</body>
</html>
"""

soup = BeautifulSoup(html, 'html.parser')

title = soup.find('title').text
header = soup.find('h1').text
paragraph = soup.find('p').text
link = soup.find('a')['href']

print(title)
print(header)
print(paragraph)
print(link)

Пример страницы
Заголовок страницы
Это абзац текста.
https://www.example.com

In [3]:
#как использовать функцию sleep:


import time

print("Начало программы")

# Приостановка выполнения на 3 секунды
time.sleep(3)

print("Прошло 3 секунды")

# Приостановка выполнения на 1 секунду
time.sleep(1)

print("Прошла еще 1 секунда")

# Приостановка выполнения на 0.5 секунды
time.sleep(0.5)

print("Прошла еще 0.5 секунды")

print("Конец программы")


#В этом примере программа будет останавливаться на указанное количество секунд с помощью функции time.sleep(). 
#Это может быть полезно, например, для создания паузы между выводом сообщений или выполнением других операций.

Начало программы
Прошло 3 секунды
Прошла еще 1 секунда
Прошла еще 0.5 секунды
Конец программы

In [4]:
#Декоратор dataclass позволяет определить класс с атрибутами и методами, а также автоматически создает специальные методы, такие как __init__, __repr__, __eq__, __ne__, __hash__ и другие. Эти методы позволяют работать с экземплярами класса как с обычными объектами данных.

#Вот пример использования декоратора dataclass:

from dataclasses import dataclass

@dataclass
class Person:
    name: str
    age: int
    city: str

# Создание экземпляра класса
person = Person("John", 30, "New York")

# Вывод информации о человеке
print(person.name)
print(person.age)
print(person.city)


#В этом примере мы создаем класс Person с помощью декоратора dataclass. 
#У этого класса есть три атрибута: name, age и city. 
#Мы можем создать экземпляр класса и работать с его атрибутами как с обычными переменными.

John
30
New York

# Как собрать данные с сайте в ограниченном объеме

In [7]:
years_company_urls = [] 
from selenium import webdriver

driver = webdriver.Chrome()

#Метод, который создает экземпляр веб-драйвера для браузера Chrome. 
#Если вы хотите использовать другой браузер, вам нужно будет изменить эту строку на соответствующий метод (например, webdriver.Firefox() для Firefox).
for u in range (400, 420):
    url0 = "https://e-disclosure.ru/portal/company.aspx?id=" + str(u)
    driver.get(url0)
    driver.implicitly_wait(30)
    years = None
    res = None

    try: 
        years = driver.execute_script('return edCompanyEventList._data["years"]') # ТУТ МЫ ПРОХОДИМСЯ ПО ГОДАМ 
    except:
        pass
    if years:
        for year in years:
            if years != 0:
                res = 'https://e-disclosure.ru/Event/Page?companyId=' + str(u) + "&year=" + str(year) + "&attempt=1"
                years_company_urls.append(res) 

years_company_urls

[]

In [8]:
res

In [9]:

#re в Python - это модуль, который предоставляет функции для работы с регулярными выражениями. 
#Регулярные выражения позволяют искать и сопоставлять строки с определенным шаблоном. 
#Модуль re включает в себя функции для поиска, замены и разделения строк на основе заданных шаблонов.

import re

In [11]:
#Пример использования модуля re в Python для поиска строки "jupiter":

text = "I love exploring the planets of our solar system, especially jupiter."

pattern = r"jupiter"

result = re.search(pattern, text)

if result:
    print("String 'jupiter' found in the text.")
else:
    print("String 'jupiter' not found in the text.")


#В этом примере мы импортируем модуль re и определяем текст, в котором мы хотим найти строку "jupiter". 
#Затем мы создаем шаблон с помощью регулярного выражения "jupiter". Метод re.search() ищет первое совпадение шаблона в тексте. 
#Если совпадение найдено, выводится сообщение "String 'jupiter' found in the text.", 
#в противном случае выводится сообщение "String 'jupiter' not found in the text.".

String 'jupiter' found in the text.

In [13]:
import pandas as pd

df = pd.DataFrame(columns = ['URL', 'ID', 'YEAR'])
i = 0
for url in years_company_urls:
    page = requests.get(url) 
    soup = BeautifulSoup(page.text, 'lxml')
    for link in soup.find_all('a'):
        if link.text == 'Решения общих собраний участников (акционеров)' or link.text == 'Решения совета директоров (наблюдательного совета)' in link.get('href'):
            #if i >= 10:
            #   print("break")
            #    break
            a = re.split(r'==([^<>]+)&', url.replace("&year=", "=="))
            b = re.split(r'=([^<>]+)==', url.replace("&year=", "=="))
            df = df.append({'URL' : link.get('href'), 'ID' : b[1], 'YEAR' : a[1]},ignore_index = True)
            i += 1
            print(i)
            
df

Empty DataFrame
Columns: [URL, ID, YEAR]
Index: []

In [14]:
df

Empty DataFrame
Columns: [URL, ID, YEAR]
Index: []


**GetNews() в Jupiter** - это функция, используется для получения новостей или информации из какого-то источника в среде Jupiter Notebook. Она может быть написана на языке программирования Python и выполнять запросы к определенному API или веб-сайту для получения новостей. Без дополнительной информации о том, как именно эта функция реализована и какие параметры она принимает, сложно дать более конкретную помощь.

Без дополнительной информации о том, как именно функция GetNews() реализована и какие параметры она принимает, сложно дать конкретную схему работы. Однако, в общих чертах, схема работы функции GetNews() в Python может выглядеть следующим образом:

1. Импортирование необходимых модулей и библиотек.
2. Определение функции GetNews() с необходимыми параметрами.
3. Создание запроса к определенному API или веб-сайту для получения новостей.
4. Обработка полученных данных (например, парсинг JSON-ответа или HTML-страницы).
5. Возврат результатов новостей или информации.

Примерная схема работы функции GetNews() в Python может выглядеть следующим образом:

In [15]:

import requests

def GetNews(api_key, source):
    url = f"https://api.example.com/news?api_key={api_key}&source={source}"
    response = requests.get(url)
    data = response.json()
    
    news = []
    for article in data['articles']:
        news.append(article['title'])
    
    return news
#В этом примере функция GetNews() принимает два параметра: api_key (ключ API) и source (источник новостей). 
#Затем создается URL-запрос к API с использованием переданных параметров. 
#Полученный ответ обрабатывается в формате JSON, и из него извлекаются заголовки новостей. 
#Результатом работы функции является список заголовков новостей.

In [16]:
def GetNews(url0):
    
    page0 = requests.get(url0)
    soup0 = BeautifulSoup(page0.text, 'lxml')
    
    company_name = ''
    short_company_name = ''
    location = ''
    adress_EGRUL = ''
    adress = ''
    reg_date = ''
    number_OGRN = ''
    INN = ''
    reg_authority = ''
    name_managing_org = ''
    phone = ''
    url_  = ''
    id_ = ''



    company_name_td = soup0.find('td', text='Полное наименование компании')
    if company_name_td:
        company_name = company_name_td.find_next_sibling('td').strong.text

    short_company_name_td = soup0.find('td', text='Сокращенное наименование компании')
    if short_company_name_td:
        short_company_name = short_company_name_td.find_next_sibling('td').strong.text

    location_td = soup0.find('td', text='Место нахождения')
    if location_td:
        location = location_td.find_next_sibling('td').strong.text

    adress_EGRUL_td = soup0.find('td', text='Адрес Субъекта раскрытия, указанный в ЕГРЮЛ')
    if adress_EGRUL_td:
        adress_EGRUL = adress_EGRUL_td.find_next_sibling('td').strong.text

    adress_td = soup0.find('td', text='Адрес (почтовый адрес)')
    if adress_td:
        adress = adress_td.find_next_sibling('td').strong.text

    reg_date_td = soup0.find('td', text='Дата государственной регистрации')
    if reg_date_td:
        reg_date = reg_date_td.find_next_sibling('td').strong.text

    number_OGRN_td = soup0.find('td', text='Номер Государственной регистрации (ОГРН)')
    if number_OGRN_td:
        number_OGRN = number_OGRN_td.find_next_sibling('td').strong.text

    INN_td = soup0.find('td', text='ИНН')
    if INN_td:
        INN = INN_td.find_next_sibling('td').strong.text

    reg_authority_td = soup0.find('td', text='Зарегистрировавший орган')
    if reg_authority_td:
        reg_authority = reg_authority_td.find_next_sibling('td').strong.text

    name_managing_org_td = soup0.find('td', text='Наименование управляющей организации')
    if name_managing_org_td:
        name_managing_org = name_managing_org_td.find_next_sibling('td').strong.text

    phone_td = soup0.find('td', text='Телефон управляющей организации')
    if phone_td:
        phone = phone_td.find_next_sibling('td').strong.text

    url_td = soup0.find('td', text='Адрес страницы в сети Интернет')
    if url_td:
        url_ = url_td.find_next_sibling('td').strong.text
    
    id_ = re.split(r'=([^<>]+)', url0)
    id_ = id_[1]
    


    return company_name, short_company_name, location, adress_EGRUL, adress, reg_date, number_OGRN, INN, reg_authority,name_managing_org,phone, url_, url0, id_

In [17]:
full_urls = []

for u in range (400, 420):
    res = 'https://e-disclosure.ru/portal/company.aspx?id=' + str(u)
    full_urls.append(res) 

full_urls

['https://e-disclosure.ru/portal/company.aspx?id=400',
 'https://e-disclosure.ru/portal/company.aspx?id=401',
 'https://e-disclosure.ru/portal/company.aspx?id=402',
 'https://e-disclosure.ru/portal/company.aspx?id=403',
 'https://e-disclosure.ru/portal/company.aspx?id=404',
 'https://e-disclosure.ru/portal/company.aspx?id=405',
 'https://e-disclosure.ru/portal/company.aspx?id=406',
 'https://e-disclosure.ru/portal/company.aspx?id=407',
 'https://e-disclosure.ru/portal/company.aspx?id=408',
 'https://e-disclosure.ru/portal/company.aspx?id=409',
 'https://e-disclosure.ru/portal/company.aspx?id=410',
 'https://e-disclosure.ru/portal/company.aspx?id=411',
 'https://e-disclosure.ru/portal/company.aspx?id=412',
 'https://e-disclosure.ru/portal/company.aspx?id=413',
 'https://e-disclosure.ru/portal/company.aspx?id=414',
 'https://e-disclosure.ru/portal/company.aspx?id=415',
 'https://e-disclosure.ru/portal/company.aspx?id=416',
 'https://e-disclosure.ru/portal/company.aspx?id=417',
 'https://e-disclosure.ru/portal/company.aspx?id=418',
 'https://e-disclosure.ru/portal/company.aspx?id=419']

In [18]:
news = [] 
# for link in full_urls_4:
for link in full_urls:
    res = GetNews(link)
    news.append(res)

/var/folders/jz/dz76_y4s3h7110gdbqbm8jc40000gn/T/ipykernel_28062/4107245778.py:22: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  company_name_td = soup0.find('td', text='Полное наименование компании')
/var/folders/jz/dz76_y4s3h7110gdbqbm8jc40000gn/T/ipykernel_28062/4107245778.py:26: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  short_company_name_td = soup0.find('td', text='Сокращенное наименование компании')
/var/folders/jz/dz76_y4s3h7110gdbqbm8jc40000gn/T/ipykernel_28062/4107245778.py:30: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  location_td = soup0.find('td', text='Место нахождения')
/var/folders/jz/dz76_y4s3h7110gdbqbm8jc40000gn/T/ipykernel_28062/4107245778.py:34: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  adress_EGRUL_td = soup0.find('td', text='Адрес Субъекта раскрытия, указанный в ЕГРЮЛ')
/var/folders/jz/dz76_y4s3h7110gdbqbm8jc40000gn/T/ipykernel_28062/4107245778.py:38: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  adress_td = soup0.find('td', text='Адрес (почтовый адрес)')
/var/folders/jz/dz76_y4s3h7110gdbqbm8jc40000gn/T/ipykernel_28062/4107245778.py:42: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  reg_date_td = soup0.find('td', text='Дата государственной регистрации')
/var/folders/jz/dz76_y4s3h7110gdbqbm8jc40000gn/T/ipykernel_28062/4107245778.py:46: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  number_OGRN_td = soup0.find('td', text='Номер Государственной регистрации (ОГРН)')
/var/folders/jz/dz76_y4s3h7110gdbqbm8jc40000gn/T/ipykernel_28062/4107245778.py:50: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  INN_td = soup0.find('td', text='ИНН')
/var/folders/jz/dz76_y4s3h7110gdbqbm8jc40000gn/T/ipykernel_28062/4107245778.py:54: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  reg_authority_td = soup0.find('td', text='Зарегистрировавший орган')
/var/folders/jz/dz76_y4s3h7110gdbqbm8jc40000gn/T/ipykernel_28062/4107245778.py:58: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  name_managing_org_td = soup0.find('td', text='Наименование управляющей организации')
/var/folders/jz/dz76_y4s3h7110gdbqbm8jc40000gn/T/ipykernel_28062/4107245778.py:62: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  phone_td = soup0.find('td', text='Телефон управляющей организации')
/var/folders/jz/dz76_y4s3h7110gdbqbm8jc40000gn/T/ipykernel_28062/4107245778.py:66: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  url_td = soup0.find('td', text='Адрес страницы в сети Интернет')

In [19]:
df1 = pd.DataFrame(news)

In [20]:
df1.columns = ['company_name', 'short_company_name', 'location', 'adress_EGRUL', 'adress', 
              'reg_date', 'number_OGRN', 'INN', 'reg_authority', 'name_managing_org', 'phone',
              'url', 'company_link',"ID"]

In [21]:
df1

,company_name,short_company_name,location,adress_EGRUL,adress,reg_date,number_OGRN,INN,reg_authority,name_managing_org,phone,url,company_link,ID
0,,,,,,,,,,,,,https://e-disclosure.ru/portal/company.aspx?id...,400
1,,,,,,,,,,,,,https://e-disclosure.ru/portal/company.aspx?id...,401
2,,,,,,,,,,,,,https://e-disclosure.ru/portal/company.aspx?id...,402
3,,,,,,,,,,,,,https://e-disclosure.ru/portal/company.aspx?id...,403
4,,,,,,,,,,,,,https://e-disclosure.ru/portal/company.aspx?id...,404
5,,,,,,,,,,,,,https://e-disclosure.ru/portal/company.aspx?id...,405
6,,,,,,,,,,,,,https://e-disclosure.ru/portal/company.aspx?id...,406
7,,,,,,,,,,,,,https://e-disclosure.ru/portal/company.aspx?id...,407
8,,,,,,,,,,,,,https://e-disclosure.ru/portal/company.aspx?id...,408
9,,,,,,,,,,,,,https://e-disclosure.ru/portal/company.aspx?id...,409
10,,,,,,,,,,,,,https://e-disclosure.ru/portal/company.aspx?id...,410
11,,,,,,,,,,,,,https://e-disclosure.ru/portal/company.aspx?id...,411
12,,,,,,,,,,,,,https://e-disclosure.ru/portal/company.aspx?id...,412
13,,,,,,,,,,,,,https://e-disclosure.ru/portal/company.aspx?id...,413
14,,,,,,,,,,,,,https://e-disclosure.ru/portal/company.aspx?id...,414
15,,,,,,,,,,,,,https://e-disclosure.ru/portal/company.aspx?id...,415
16,,,,,,,,,,,,,https://e-disclosure.ru/portal/company.aspx?id...,416
17,,,,,,,,,,,,,https://e-disclosure.ru/portal/company.aspx?id...,417
18,,,,,,,,,,,,,https://e-disclosure.ru/portal/company.aspx?id...,418
19,,,,,,,,,,,,,https://e-disclosure.ru/portal/company.aspx?id...,419

In [22]:
df_merge_col = pd.merge(df, df1, on='ID')

df_merge_col

Empty DataFrame
Columns: [URL, ID, YEAR, company_name, short_company_name, location, adress_EGRUL, adress, reg_date, number_OGRN, INN, reg_authority, name_managing_org, phone, url, company_link]
Index: []

In [23]:
df_merge_col.to_csv("RES_FINAL_1.csv", index=False)

In [25]:
import nltk
from nltk.tokenize import sent_tokenize
import matplotlib.pyplot as plt
from nltk.probability import FreqDist
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [26]:
def GetWord(url0):
    
    page0 = requests.get(url0)
    soup0 = BeautifulSoup(page0.text, 'lxml')
    word = ''
    word_td = soup0.find('div', attrs={"id": "cont_wrap"}).get_text()

    return word_td, url0

In [27]:
words = [] 
for link in df_merge_col['URL'].tolist():
    res = GetWord(link)
    words.append(res)
df_word = pd.DataFrame(words)

In [28]:
df_word.columns = ['word', "URL"]

ValueError: Length mismatch: Expected axis has 0 elements, new values have 2 elements

In [29]:
df_word

Empty DataFrame
Columns: []
Index: []