# Расчет центрального положения величины

### План урока:
* Зачем нужно определять центральное положение величины?
* Метрики центрального положения, их особенности и отличия.
* Практика в jupyter notebook.

#### Зачем нужно определять центральное положение величины
Это помогает понять, какие значения для каждого признака являются типичными.

## 1. Синтетические данные

In [1]:
import numpy as np
from scipy import stats

In [2]:
# Количество товаров в корзине пользователя на маркетплейсе
x = [10, 2, 2, 5, 26, 6]

### Выборочное среднее:

$$\bar{x} = \frac{\sum_{i = 1}^{n}x_i}{n}$$
$n$ – число элементов выборки

$x_{i}$ – элемент выборки

In [3]:
mean = sum(x) / len(x)
mean

8.5

In [4]:
mean = np.mean(x)
mean

np.float64(8.5)

---
Выборочное среднее сильно чувствительно к выбросам.

In [5]:
# добавили пользователя-перекупщика
y = [10, 2, 2, 5, 26, 6, 100]

In [6]:
np.mean(y)

np.float64(21.571428571428573)

### Усеченное среднее

Усеченное среднее — это среднее значение набора данных, рассчитанное после удаления определенного процента наименьших и наибольших значений из набора данных.

In [7]:
stats.trim_mean(y, 0.2)

np.float64(9.8)

### Взвешенное среднее:

$$\bar{x} = \frac{\sum_{i = 1}^{n}x_i w_i}{\sum_{i = 1}^{n}w_i}$$
$n$ – число элементов выборки

$x_{i}$ – элемент выборки

$w_{i}$ – вес элемента выборки

---
Взвешенное среднее используют тогда, когда некоторые значения интересующей нас переменной x <b>более важны</b>, чем другие.

Мы присоединяем вес $w_{i}$ к каждому из значений $x_{i}$ в нашей выборке для того, чтобы учесть эту важность.

In [8]:
# преобразуем list в numpy массив
y = np.array([10, 2, 2, 5, 26, 6, 100])
w = np.array([0.2, 0.5, 0.5, 0.4, 0.2, 0.3, 0.1])

In [9]:
wm = y.dot(w) / sum(w)
wm

np.float64(10.454545454545453)

In [10]:
wm = np.average(y, weights=w)
wm

np.float64(10.454545454545453)

---
Взвешенное среднее часто можно встретить в физике или экономике.

<b>Средняя скорость тела</b>

$$v_{cp} = \frac{\sum_{i = 1}^{n}t_i v_i}{\sum_{i = 1}^{n}t_i}$$

$v_{i}$ – скорость тела на $i$-м промежутке

$t_{i}$ – длительность $i$-го промежутка

### Медиана:

Медиана – число, которое находится в середине выборки, если ее упорядочить по возрастанию, то есть такое число, что половина из элементов набора не меньше него, а другая половина не больше.

In [11]:
y = [10, 2, 2, 5, 26, 6, 100]

In [12]:
# нечетное число элементов выборки
sorted(y) # 6.0

[2, 2, 5, 6, 10, 26, 100]

In [13]:
# четное число элементов выборки
sorted(x) # 5.5

[2, 2, 5, 6, 10, 26]

In [14]:
np.median(y), np.median(x)

(np.float64(6.0), np.float64(5.5))

### Мода:

Мода – это элемент, который чаще всего встречается в данной выборке

In [15]:
y = [10, 2, 2, 5, 26, 6, 100]

In [16]:
mode = stats.mode(y)
mode

ModeResult(mode=np.int64(2), count=np.int64(2))

---
Мода как средняя величина употребляется чаще для данных, имеющих нечисловую природу.

In [17]:
# бинарные данные
b = [0, 1, 0, 0, 1]

In [18]:
mode = stats.mode(b)
mode

ModeResult(mode=np.int64(0), count=np.int64(3))

## 2. Боевой датасет

In [19]:
import pandas as pd

In [20]:
data = pd.read_csv('data.csv')
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [21]:
data.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

<b>Выборочное среднее:</b>

In [22]:
data.Sales

0       261.9600
1       731.9400
2        14.6200
3       957.5775
4        22.3680
          ...
9795      3.7980
9796     10.3680
9797    235.1880
9798     26.3760
9799     10.3840
Name: Sales, Length: 9800, dtype: float64

In [23]:
mean = np.mean(data.Sales)
mean

np.float64(230.76905945918367)

In [24]:
data.Sales.mean()

np.float64(230.76905945918367)

<b>Усеченное среднее:</b>

In [25]:
len(data.Sales) * 0.1, len(data.Sales) * 0.01

(980.0, 98.0)

In [26]:
stats.trim_mean(data.Sales, 0.1), stats.trim_mean(data.Sales, 0.01)

(np.float64(113.65588941326531), np.float64(188.935317544773))

<b>Медиана:</b>

In [27]:
median = np.median(data.Sales),
median

(np.float64(54.489999999999995),)

In [28]:
data.Sales.median()

np.float64(54.489999999999995)

<b>Мода:</b>

Мода как средняя величина употребляется чаще для данных, имеющих нечисловую природу.

In [29]:
data.State.mode()

0    California
Name: State, dtype: str

In [30]:
len(data[data.State == 'California'])

1946

---
## Итоги:
1. В зависимости от выборки, т.е. наличия в ней выбросов и различных типов данных, следует тщательно выбирать меру среднего.
2. Выборочное среднее сильно чувствительно к выбросам.
3. В датасетах с выбросами уместнее будет в качестве меры центрального положения выбирать:
    - взвешенное среднее;
    - усеченное среднее;
    - медиану.
4. Для данных, имеющих нечисловую природу (категориальные), можно воспользоваться модой.